# Generated by Django 5.1.dev20231119153146 on 2023-11-21 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoTitle', models.CharField(max_length=100)),
                ('photoUrl', models.CharField(max_length=1000)),
                ('photoDescription', models.CharField(max_length=2000)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SparkSpaceAPI.collection')),
            ],
        ),
    ]
